### ISSUE TITLE
your jypeter file dosen't work 

### ISSUE THREAD

**Issue by MA-BOUSSOUALEF** [MA-BOUSSOUALEF/Classification-of-Heartbeats#3]
your jypeter file dosen't work  i think you have a probleme in google colab

**Comment by branis192** [comment]
my jypeter work , i dont have a problem

**Comment by MA-BOUSSOUALEF** [comment]
i don't speak about code .The format of the file is not acceptable. 
Even when I download the file, it gives me an error when I try to open it.
![image](https://github.com/user-attachments/assets/cec658f3-7a35-42ec-9d92-8d033ce9dab1)

**Comment by branis192** [comment]
the format is .ipynb the same as always
